# Generated by Django 6.0 on 2025-12-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='department',
            new_name='Departments',
        ),
    ]
