# Generated by Django 6.0 on 2026-01-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Doc_name',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='Doc_specs',
            new_name='doc_specs',
        ),
    ]
